### ISSUE TITLE
Cannot read property 'manifest.js' of undefined

### ISSUE THREAD

**Issue by felipekm** [Microsoft/vscode-recipes#110]
I'm using your guys recipe to run an app with Next.JS and when I hit `F5` in any `launch.json` config, it outputs an `Internal Server Error`:

Stack:
```
TypeError: Cannot read property 'manifest.js' of undefined
    at Head.getChunkPreloadLink (/Users/felipemello/workspace/Pling/next-webmail/node_modules/next/dist/server/document.js:116:32)
    at Head.getPreloadMainLinks (/Users/felipemello/workspace/Pling/next-webmail/node_modules/next/dist/server/document.js:132:54)
    at Head.render (/Users/felipemello/workspace/Pling/next-webmail/node_modules/next/dist/server/document.js:182:48)
    at resolve (/usr/local/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/usr/local/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/usr/local/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToStaticMarkup (/usr/local/lib/node_modules/react-dom/cjs/react-dom-server.node.development.js:2512:25)
    at _callee3$ (/usr/local/lib/node_modules/next/dist/server/render.js:223:100)
    at tryCatch (/usr/local/lib/node_modules/next/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/next/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/next/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/next/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

`launch.json`:

``` json
{
  "version": "0.2.0",
  "configurations": [
  {
      "type": "chrome",
      "request": "launch",
      "name": "Next: Chrome",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    },
    {
      "type": "node",
      "request": "launch",
      "name": "Next: Node",
      "runtimeExecutable": "next",
      "runtimeArgs": [
        "--inspect"
      ],
      "port": 9229,
      "console": "integratedTerminal"
    }
  ],
  "compounds": [
    {
      "name": "Next: Full",
      "configurations": ["Next: Node", "Next: Chrome"]
    }
  ]
}

```

Someone have any idea?

**Comment by auchenberg** [comment]
What happens if you run `next --inspect` from your integrated terminal, @felipekm? This looks like an next js error.

**Comment by connor4312** [comment]
I cannot reproduce this and there hasn't been followup info in a little while
