### ISSUE TITLE
Next.js recipe fails on Windows

### ISSUE THREAD

**Issue by devuxer** [Microsoft/vscode-recipes#146]
Following the next.js recipe, my launch.json has a "Next: Node" configuration with this setting:

`"runtimeExecutable": "next"`

This is not working for me on Windows. I get the following error:

> Cannot find runtime 'next' on PATH. Make sure to have 'next' installed.

I do have 'next' installed for my project via `npm install next`.

If I do the following, it basically solves the problem, though it does have one undesirable side effect (see below):

1. Add `"debug": "next --inspect"` to package.json > scripts
2. Change my launch.json to this:
    ```json
     {
         "name": "Next: Node",
         "type": "node",
         "request": "launch",
         "runtimeExecutable": "npm",
         "runtimeArgs": ["run", "debug"],
         "port": 9229,
         "console": "integratedTerminal"
    }
    ```

The problem I'm having with this is that when I *stop* the debugger (using the VSCode debugger stop button), I get an `ELIFECYCLE` error with exit status 1 (see log below).

Is it normal to get this error? If not, any idea why it's occurring and how to avoid it?

**Log**

> 0 info it worked if it ends with ok
> 1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\MyName\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'debug' ]
> 2 info using npm@6.4.1
> 3 info using node@v8.11.3
> 4 verbose run-script [ 'predebug', 'debug', 'postdebug' ]
> 5 info lifecycle my-project@1.0.0\~predebug: my-project@1.0.0
> 6 info lifecycle my-project@1.0.0\~debug: my-project@1.0.0
> 7 verbose lifecycle my-project@1.0.0\~debug: unsafe-perm in lifecycle true
> 8 verbose lifecycle my-project@1.0.0\~debug: PATH: C:\Users\MyName\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\MyName\Documents\Projects\Current\MyProject\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseHg\;C:\Users\MyName\AppData\Local\Microsoft\WindowsApps;C:\Users\MyName\AppData\Local\GitHubDesktop\bin;C:\Users\MyName\AppData\Roaming\npm;C:\Program Files\PostgreSQL\10\bin\;C:\Program Files\PostgreSQL\10\lib\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\PHP\v7.1\;C:\Program Files\nodejs\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\Users\MyName\AppData\Local\Microsoft\WindowsApps;C:\Users\MyName\AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\MyName\AppData\Local\Microsoft\WindowsApps;C:\Users\MyName\AppData\Roaming\npm;C:\Users\MyName\AppData\Local\Programs\Microsoft VS Code\bin
> 9 verbose lifecycle my-project@1.0.0\~debug: CWD: C:\Users\MyName\Documents\Projects\Current\MyProject
> 10 silly lifecycle my-project@1.0.0\~debug: Args: [ '/d /s /c', 'next --inspect' ]
> 11 silly lifecycle my-project@1.0.0\~debug: Returned: code: 1  signal: null
> 12 info lifecycle my-project@1.0.0\~debug: Failed to exec debug script
> 13 verbose stack Error: my-project@1.0.0 debug: `next --inspect`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\MyName\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at EventEmitter.emit (events.js:214:7)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\MyName\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at emitTwo (events.js:126:13)
> 13 verbose stack     at ChildProcess.emit (events.js:214:7)
> 13 verbose stack     at maybeClose (internal/child_process.js:925:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> 14 verbose pkgid my-project@1.0.0
> 15 verbose cwd C:\Users\MyName\Documents\Projects\Current\MyProject
> 16 verbose Windows_NT 10.0.17134
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\MyName\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "debug"
> 18 verbose node v8.11.3
> 19 verbose npm  v6.4.1
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error my-project@1.0.0 debug: `next --inspect`
> 22 error Exit status 1
> 23 error Failed at the my-project@1.0.0 debug script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by devuxer** [comment]
Ahh, it seems the solution is to use `"runtimeExecutable": "${workspaceFolder}/node_modules/.bin/next"`, as shown in [this comment](https://github.com/Microsoft/vscode-recipes/issues/103#issuecomment-404466067).

**Comment by devuxer** [comment]
Ahh #2, now I see there's a [pull request](https://github.com/Microsoft/vscode-recipes/pull/141) that uses npx. This works for me, so I'm closing this.
