### ISSUE TITLE
Cannot find runtime 'next' on PATH. Make sure to have 'next' installed.

### ISSUE THREAD

**Issue by Blanen** [Microsoft/vscode-recipes#195]
This is concerning the next.js recipe, on the next:node mode.

![image](https://user-images.githubusercontent.com/7236824/53246036-d0193380-36af-11e9-9e59-e6aec8594df5.png)
Also, the "official sample app" url doesn't work : `git@github.com:now-examples/nextgram.git`
![image](https://user-images.githubusercontent.com/7236824/53246169-356d2480-36b0-11e9-8c45-1c52ecf5621b.png)

Launch.json is literally the one from the readme.

The next:chrome debugger works but only if I start the application myself too, while I would assume it should start it up.

**Comment by weijian19391** [comment]
@Blanen not sure if you have resolved that issue of not able to find runtime 'next', but there are two ways to resolve it.

1. Install next, react and react-dom globally, such that next binary can be found
2. change your runtimeExecutable parameter to the following: 
`"runtimeExecutable": "${workspaceFolder}/node_modules/next/dist/bin/next",`

**Comment by vvo** [comment]
Hey there, I created a PR on Next.js docs to have Next.js debugging working in either Chrome DevTools or VSCode, appreciate any feedback you have when trying it out on the PR: https://github.com/zeit/next.js/pull/10807/files?short_path=bfcc096#diff-bfcc096377efef455dd348d059704209

I choosed to only attach to the debugger from VSCode instead of trying to completely launch next from VSCode because in many occasions your Next.js application might be loaded by docker/overmind/foreman/heroku local... Let me know what you think!

**Comment by Vadorequest** [comment]
I can confirm that following the tutorial at https://github.com/Microsoft/vscode-recipes/tree/master/Next-js doesn't work, I get `Cannot find runtime 'next' on PATH. Make sure to have 'next' installed. `.

Following above advice and using `"runtimeExecutable": "${workspaceFolder}/node_modules/next/dist/bin/next",` doesn't work either. 

Here is what I get when running `'Next: Node' configuration` (or hit F5)

```
 /Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next --inspect 

 vadorequest@Ambroises-MBP-001  ~/dev/next-right-now   vscode ● ? ⍟33 
 ✔   /Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next --inspect 
/Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next:25
  `);process.exit(0);}const command=foundCommand?args._[0]:defaultCommand;const forwardedArgs=foundCommand?args._.slice(1):args._;if(args['--inspect'])throw new Error(`--inspect flag is deprecated. Use env variable NODE_OPTIONS instead: NODE_OPTIONS='--inspect' next ${command}`);// Make sure the `next <subcommand> --help` case is covered
                                                                                                                                                       ^

Error: --inspect flag is deprecated. Use env variable NODE_OPTIONS instead: NODE_OPTIONS='--inspect' next dev
    at Object.<anonymous> (/Users/vadorequest/dev/next-right-now/node_modules/next/dist/bin/next:25:158)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Shortly followed by 
![image](https://user-images.githubusercontent.com/3807458/83522438-f51a6a00-a4e0-11ea-8594-1aa470382d02.png)


---

Following the doc at https://github.com/vercel/next.js/pull/10807/files, the process attaches correctly to the running Node.js instance, but it ignores all breakpoints set on TS files (.ts/.tsx)

**Comment by connor4312** [comment]
Next.js recipe has been updated
