### ISSUE TITLE
debuggerPort does not work for Ruby on Rails debugging in VS Cod

### ISSUE THREAD

**Issue by a21862** [microsoft/vscode-recipes#291]
when I do "Ruby on Rails debugging in VS Code", the remote port "1234" is always used. 

I tried to set "debuggerPort" to a different number, so I launch a new vs code with another user account to debug a second rails app on the same remote server . However, it does not work.  The below exception happens 

Fatal exception in DebugThread loop: Address already in use - bind(2) for "127.0.0.1" port 1234
Backtrace:
/home/user01/.rvm/gems/ruby-2.4.4/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:147:in `initialize'
  from: /home/user01/.rvm/gems/ruby-2.4.4/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:147:in `new'
  from: /home/user01/.rvm/gems/ruby-2.4.4/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:147:in `block (2 levels) in _start_control_common'
  from: /home/user01/.rvm/gems/ruby-2.4.4/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:192:in `notify_dispatcher_if_needed'
  from: /home/user01/.rvm/gems/ruby-2.4.4/gems/ruby-debug-ide-0.7.2/lib/ruby-debug-ide.rb:146:in `block in _start_control_common'

Wondering, how can I set host and port parameters of rdebug-ide within VS Code ？

**Comment by progpyftk** [comment]
Any comment? Having the same issue.

**Comment by progpyftk** [comment]
I had the same problem!

It has just worked here. SO: Windows.

Using the most recent versions of ruby-debug-ide and debase.

You just need to kill the process which is "using" the port 1234. 

Windows:
First find the PID: netstat -a -n -o | find  <port>
ex: netstat -a -n -o | find "1234"
then copy the PID number.

Kill the PID
taskkill /PID <PID>  /F
