### ISSUE TITLE
Docker-TypeScript:  TSC running outside of the container?

### ISSUE THREAD

**Issue by synthecypher** [Microsoft/vscode-recipes#60]
So I'm looking at the `Launch in Docker` debug configuration at the moment and it produces this error.

```
web_1  | Error: Cannot find module '/server/dist/index.js'
web_1  |     at Function.Module._resolveFilename (module.js:538:15)
web_1  |     at Function.Module._load (module.js:468:25)
web_1  |     at Function.Module.runMain (module.js:684:10)
web_1  |     at startup (bootstrap_node.js:187:16)
web_1  |     at bootstrap_node.js:608:3
web_1  | [nodemon] app crashed - waiting for file changes before starting...
```

I assume this is because the `tsc-watch` tasks is not starting before this runs and therefore the compiled output is not available in the `/dist` of the container.

Why does this project choose to have the `tsc-watch` task run outside the container where as things like running the server via `nodemon` inside the container?

Surely for a more portable development setup it would be better to run everything inside containers therefore making Docker the only dependency to run the project?

**Comment by pcmanprogrammeur** [comment]
What is the solution please ?

**Comment by als9xd** [comment]
This happened to me because I forgot to remove dist from .dockerignore

**Comment by connor4312** [comment]
We no longer have a Docker-TypeScript recipe as it has been supplanted by [Remote-Containers](https://code.visualstudio.com/docs/remote/containers) functionality.
